name: Run Playwright Tests with Flaky Simulation

on: [push, pull_request]  # Trigger on push or pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Get the repository code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify Python version

      - name: Install Dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate virtual environment
          pip install playwright pytest matplotlib pandas  # Install required libraries
          playwright install  # Install Playwright browsers

      - name: Initialize CSV File
        run: |
          mkdir -p artifacts  # Ensure artifacts directory exists
          echo "timestamp,url,passed,status" > artifacts/test_results.csv  # Create empty CSV file

      - name: Run Playwright Tests 20 Times
        run: |
          source venv/bin/activate
          
          # Run tests 20 times and log results
          for i in {1..20}; do pytest test_flaky_playwright.py || true; done

      - name: Generate Test Report
        run: |
          source venv/bin/activate
          python test_flaky_playwright.py  # Generate the test report

      - name: Debug - Check if Artifacts Exist
        run: |
          ls -lah artifacts  # List all files to ensure they exist before upload
          cat artifacts/test_results.csv | head -n 20  # Show first 20 rows of CSV for debugging

      - name: Upload Test Report and CSV Data
        uses: actions/upload-artifact@v4
        with:
          name: flaky-test-results
          path: artifacts/
