name: Run Playwright Tests with Flaky Simulation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install playwright pytest matplotlib pandas
          playwright install

      - name: Run Playwright Tests 100 Times
        run: |
          source venv/bin/activate
          rm -f test_results.csv  # Clear previous results
          for i in {1..100}; do pytest test_flaky_playwright.py || true; done

      - name: Generate Test Report
        run: |
          source venv/bin/activate
          python test_flaky_playwright.py  # This runs the report function

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: flaky-test-report
          path: test_report.png
